### ISSUE TITLE
JCenter will shutdown. Do you plan to move to another repository?

### ISSUE THREAD

**Issue by Vanamas** [optimove-tech/Optimove-SDK-Android#2]
The JCenter repository will be closed on Jan 31 2022 (see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Do you plan to move the SDK to another repository?

**Comment by KonstantinOptimove** [comment]
Starting from version 4.0.0, the SDK is distributed to Maven Central.
