### ISSUE TITLE
Build fails with 4.2.0

### ISSUE THREAD

**Issue by vinaywadhwa** [optimove-tech/Optimove-SDK-Android#7]
Build fails with AAPT error `android:dataExtractionRules not found` in the manifest-merge build step. Reverting to 4.1.2 fixes this. 100% reproducible.

**Comment by KonstantinOptimove** [comment]
If you consume SDK version higher or equal to 4.2.0 and your target version is lower than 31, please add `tools:remove="android:dataExtractionRules"` to the application tag of your manifest.
